spring:
  profle:
    active: dev
---
spring:
    profiles: dev
    datasource:
      url: jdbc:mysql://localhost:8889/spring
      driverClassName: com.mysql.jdbc.Driver 
      username: root
      password: root
    jpa:
      database: MYSQL
      database-platform: org.hibernate.dialect.MySQLDialect
      show-sql: true 
      hibernate:
        ddl-auto: update
    thymeleaf:
      cache: false

    logging:
      file: logs/myapp.log
      level:
        org.springframework.web: DEBUG
      properties:
          hibernate:
            dialect: org.hibernate.dialect.MySQLDialect
            hbm2ddl:
                auto: update
            temp:
                use_jdbc_metadata_defaults: false
---
spring:
    profiles: heroku
    datasource:
      driverClassName: org.postgresql.Driver
    jpa:
      database: POSTGRESQL
      hibernate:
        ddl-auto: update
      properties:
          hibernate:
            dialect: org.hibernate.dialect.PostgreSQLDialect
            hbm2ddl:
                auto: update
            temp:
                use_jdbc_metadata_defaults: false